name: run api tests

on:
  push:
    branches: "feature/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v4.1.2

       - name: Setup Java JDK
         uses: actions/setup-java@v4.2.1
         with:
           java-version: 21
           distribution: temurin
           cache: maven
         
       - name: Run Api Tests
         run: mvn test 
      
