name: run api tests

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v4.1.2

       - name: run api tests
         run: mvn test -DsuiteXmlFile="testng.xml"
      
